### ISSUE TITLE
simplejson.errors.JSONDecodeError: Unterminated string

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre/cti#16]
Good afternoon Team,

I was testing the libraries again, and they have been working fine, but around 30 mins ago I started to get the following message at the **Query** method from the **TAXIICollectionSource** class:

```
>>> from stix2 import TAXIICollectionSource, Filter
>>> from taxii2client import Server, Collection
>>> 
>>> enterprise_stix_objects = {}
>>> collection = Collection("https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/")
>>> tc_source = TAXIICollectionSource(collection , allow_custom=True)
>>> 
>>> enterprise_stix_objects['techniques'] = tc_source.query(Filter("type", "=", "attack-pattern"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/stix2/datastore/taxii.py", line 229, in query
    all_data = self.collection.get_objects(**taxii_filters_dict)["objects"]
  File "/Library/Python/2.7/site-packages/taxii2client/__init__.py", line 442, in get_objects
    params=query_params)
  File "/Library/Python/2.7/site-packages/taxii2client/__init__.py", line 816, in get
    return resp.json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Python/2.7/site-packages/simplejson/__init__.py", line 517, in loads
    return _default_decoder.decode(s)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/Library/Python/2.7/site-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/Library/Python/2.7/site-packages/simplejson/scanner.py", line 45, in _scan_once
    _scan_once, object_hook, object_pairs_hook, memo)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 194, in JSONObject
    value, end = scan_once(s, end)
  File "/Library/Python/2.7/site-packages/simplejson/scanner.py", line 47, in _scan_once
    return parse_array((string, idx + 1), _scan_once)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 250, in JSONArray
    value, end = scan_once(s, end)
  File "/Library/Python/2.7/site-packages/simplejson/scanner.py", line 45, in _scan_once
    _scan_once, object_hook, object_pairs_hook, memo)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 194, in JSONObject
    value, end = scan_once(s, end)
  File "/Library/Python/2.7/site-packages/simplejson/scanner.py", line 42, in _scan_once
    return parse_string(string, idx + 1, encoding, strict)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 69, in py_scanstring
    "Unterminated string starting at", s, begin)
simplejson.errors.JSONDecodeError: Unterminated string starting at: line 1 column 64600 (char 64599)
>>> 
```
I wonder if anything changed ??

**Comment by jburns12** [comment]
@Cyb3rWard0g - thanks for the traceback and for the heads up.

I'm checking this out right now and will let you know ASAP when it's fixed.

**Comment by Cyb3rWard0g** [comment]
It works now 👍 It must have been some bug on the library. I ran the commands again and it works 

```
>>> from stix2 import TAXIICollectionSource, Filter
>>> from taxii2client import Server, Collection
>>> 
>>> enterprise_stix_objects = {}
>>> 
>>> collection = Collection("https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/")
>>> 
>>> tc_source = TAXIICollectionSource(collection)
>>> 
>>> enterprise_stix_objects['techniques'] = tc_source.query(Filter("type", "=", "attack-pattern"))
>>> 
>>> enterprise_stix_objects['techniques'][0]
AttackPattern(type=u'attack-pattern', id=u'attack-pattern--18d4ab39-12ed-4a16-9fdb-ae311bba4a0f', created_by_ref='identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5', created='2017-12-14T16:46:06.044Z', modified='2018-04-18T17:59:24.739Z', name=u'Rc.common', description=u'During the boot process, macOS executes <code>source /etc/rc.common</code>, which is a shell script containing various utility functions. This file also defines routines for processing command-line arguments and for gathering system settings, and is thus recommended to include in the start of Startup Item Scripts (Citation: Startup Items). In macOS and OS X, this is now a deprecated technique in favor of launch agents and launch daemons, but is currently still used.\n\nAdversaries can use the rc.common file as a way to hide code for persistence that will execute on each reboot as the root user (Citation: Methods of Mac Malware Persistence).\n\nDetection: The <code>/etc/rc.common</code> file can be monitored to detect changes from the company policy. Monitor process execution resulting from the rc.common script for unusual or unknown applications or behavior.\n\nPlatforms: macOS\n\nData Sources: File monitoring, Process Monitoring\n\nPermissions Required: root', kill_chain_phases=[KillChainPhase(kill_chain_name=u'mitre-attack', phase_name=u'persistence')], external_references=[ExternalReference(source_name=u'mitre-attack', url=u'https://attack.mitre.org/wiki/Technique/T1163', external_id=u'T1163'), ExternalReference(source_name=u'Startup Items', description=u'Apple. (2016, September 13). Startup Items. Retrieved July 11, 2017.', url=u'https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/StartupItems.html'), ExternalReference(source_name=u'Methods of Mac Malware Persistence', description=u'Patrick Wardle. (2014, September). Methods of Malware Persistence on Mac OS X. Retrieved July 5, 2017.', url=u'https://www.virusbulletin.com/uploads/pdf/conference/vb2014/VB2014-Wardle.pdf')], object_marking_refs=['marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168'], x_mitre_data_sources=[u'File monitoring', u'Process Monitoring'], x_mitre_permissions_required=[u'root'], x_mitre_platforms=[u'macOS'])
>>> 
```

**Comment by Cyb3rWard0g** [comment]
Thank you for the quick response!!!

**Comment by jburns12** [comment]
Thanks again @Cyb3rWard0g . We ran into some Docker memory issues which have been resolved for the present. Let us know if you have any more problems. You've been extremely helpful!

**Comment by Cyb3rWard0g** [comment]
np @jburns12 👍 Happy to help! Thank you for providing the details. I appreciate it!! I will keep you posted. I just tested the libraries again and it is still working fine. I will close this issue. Have a good night!
